#!/bin/python
import os
from itertools import islice

wallman = open(os.path.expanduser('~/.config/wallman'), 'r')

#Parse wallman config

class profile:
    name = ""
    displayname = ""
    category = ""

categories = {}

profiles = []

wallman.readline() #Eat the first line
for wall_line in wallman:
    if ":" in wall_line and "monitors" not in wall_line and "category" not in wall_line:
        new_profile = profile()
        wall_line.replace("\n","")
        wall_line.strip()#.replace(" ","")
        split = wall_line.split(":")
        category = next(islice(wallman, 1, 2))
        category = category.split(":")[1].strip()#.replace(" ","").replace("\n","")
        if split[1]!="\n":
            new_name = split[1].strip()#.replace(" ","").replace("\n","")
            if new_name != "ignore":
                #print("Profile " + split[0] + " called:" + new_name)
                new_profile.name = split[0]
                new_profile.displayname = new_name
        else:
            #print("Profile " + split[0])
            new_profile.name = split[0]
            new_profile.displayname = split[0]

        if new_profile.name != "":
            profiles.append(new_profile)

            if category in categories:
                categories[category].append(new_profile)
            else:
                categories[category] = [new_profile]


jgmenu_new = ""
# for profile in profiles:
    # jgmenu_new += (profile.displayname + ",wallman " + profile.name + "&\n")

if "none" in categories:
    for profile in categories["none"]:
        jgmenu_new += (profile.displayname + ",wallman " + profile.name + "&\n")

for category in categories:
    if category != "none":
        jgmenu_new += category + ",^checkout(" + category + ")\n"


for category in categories:
    if category != "none":
        jgmenu_new += category + ",^tag(" + category + ")\n"
        for profile in categories[category]:
            jgmenu_new += (profile.displayname + ",wallman " + profile.name + "&\n")
        jgmenu_new += "^back()"


jgmenu_new += "\n"
jgmenu = open(os.path.expanduser('~/.config/wallman_jgmenu'),'w')
jgmenu.write(jgmenu_new)
jgmenu.close()
#print("Config Applied To Polybar - Restart Polybar to Continue")
